### ISSUE TITLE
Videos about using WSIGNA & Pancakeswap to trade or add liquidity on it

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/bounties#3]
**Reward 10.000 SIGNA**

Since we introduced the liquidity pool for Signa on Pancakeswap we should have introductory videos on how to use  BTDEX, Harvey and BSC to trade or provide liquidity to the pools.

The following videos steps are suggested :

- What is needed to wrap Signa to WSIGNA 
-- Explain what is BTDEX (short)
-- Open the market WSIGNA
--Take an offer (or make your own)

-  How to find WSIGNA
-- Show the informations on CMC and Coingecko
-- Show the page on https://www.signum.network/pancakeswap.html
-- Open the coin and pool(s) WBNB and USDT on pancakeswap

- How to send  small fraction of BNB to harvey and swap it to SIGNA
-- Send BNB from wallet to harvey
-- Swap it to SIGNA
-- Open BTDEX and open a contract (cross-chain) to buy SIGNA ( with BNB)

- How to move BNB to BSC from harvey
-- Swap Signa for BNB with harvey
-- Move BNB to Binance Wallet ( browser extension) 
-- Binance Main Chain (hint with account pattern bnb1..)
-- Move BNB from Binance Main Chain to your own account on Binance Smart Chain (BSC)

- How to wrap or unwrap BNB <> WBNB

- How to add/remove  liquidity to a pool from WSIGNA

- How to trade with a WSIGNA pool

**Definition of Done**
There is no guarantee all videos will receive the bounty, it is up to the SNA to decide if a video meets the requirements. 
The bounty will be paid only for all suggested steps. The creator can pack or unpack  the suggested steps if it seems better for him/her.

If valid the bounty will be up to 10k SIGNA and it will be paid max to 3 different video providers.
The video can be used by Signum and uploaded to the its Youtube channel

**Requirements** 

- The videos should have the same intro and credits
- Voice needs to be in a clear/good english
- Simple representation of the processes
- Each video should not be longer than 5 minutes. ( with intro/credits)

**Comment by TouchstoneTheDev** [comment]
Hi ?
